#!/bin/sh

cp -r \
  ./bat \
  ./btop \
  ./fish \
  ./MangoHud \
  ./mpv \
  ./rustfmt \
  ~/.config
cp -r ./.cargo/* ~/.cargo

printf "remember to install/update tpm plugins with"
printf "<prefix>+shift+i/<prefix>+shift+u\\n"
