#!/bin/sh

if [ ! -e ~/.tmux/plugins/tpm ]; then
  printf "tpm not found, installing to ~/.tmux/plugins/tpm\\n"
  git clone git@github.com:tmux-plugins/tpm.git ~/.tmux/plugins/tpm
fi

cp -r \
  ./alacritty \
  ./bat \
  ./btop \
  ./fish \
  ./hypr \
  ./MangoHud \
  ./mpv \
  ./rustfmt \
  ./starship.toml \
  ./tmux \
  ./waybar \
  ~/.config
cp -r ./.cargo ~/.cargo

printf "remember to install/update tpm plugins with"
printf "<prefix>+shift+i/<prefix>+shift+u\\n"
