#!/bin/sh

cp -r ~/.config/alacritty .
cp -r ~/.config/bat .
cp -r ~/.config/btop .
cp -r ~/.config/fish .
cp -r ~/.config/hypr .
cp -r ~/.config/MangoHud .
cp -r ~/.config/mpv .
cp -r ~/.config/rustfmt .
cp ~/.config/starship.toml .
cp -r ~/.config/waybar .
cp ~/.cargo/config.toml .cargo
cp -r ~/.config/tmux/tmux.conf tmux
