#!/bin/sh

cp -r ~/.config/bat/ ./
cp -r ~/.config/btop/btop.conf ~/.config/btop/themes/ ./btop/
cp ~/.config/fish/config.fish ./fish/
cp -r ~/.config/hypr/ ./
cp -r ~/.config/MangoHud/ ./
cp -r ~/.config/mpv/ ./
cp -r ~/.config/rustfmt/ ./
cp ~/.config/starship.toml ./
cp -r ~/.config/waybar/ ./
cp ~/.cargo/config.toml ./.cargo/
cp ~/.cargo/bin/cargo-inst ./.cargo/bin/
cp -r ~/.config/tmux/tmux.conf ./tmux/
cp -r ~/.config/wezterm/ ./
