#!/bin/sh

cp -r ~/.config/bat/ ./
cp -r ~/.config/btop/btop.conf ~/.config/btop/themes/ ./btop/
cp ~/.config/fish/config.fish ./fish/
cp -r ~/.config/MangoHud/ ./
cp -r ~/.config/mpv/ ./
cp -r ~/.config/rustfmt/ ./
cp ~/.cargo/config.toml ./.cargo/
cp ~/.cargo/bin/cargo-inst ./.cargo/bin/
