complete -c probe-rs -n __fish_use_subcommand -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n __fish_use_subcommand -s r -l report -r -F
complete -c probe-rs -n __fish_use_subcommand -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n __fish_use_subcommand -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n __fish_use_subcommand -s V -l version -d 'Print version'
complete -c probe-rs -n __fish_use_subcommand -f -a dap-server -d 'Debug Adapter Protocol (DAP) server. See <https://probe.rs/docs/tools/debugger/>'
complete -c probe-rs -n __fish_use_subcommand -f -a list -d 'List all connected debug probes'
complete -c probe-rs -n __fish_use_subcommand -f -a info -d 'Gets info about the selected debug probe and connected target'
complete -c probe-rs -n __fish_use_subcommand -f -a reset -d 'Resets the target attached to the selected debug probe'
complete -c probe-rs -n __fish_use_subcommand -f -a gdb -d 'Run a GDB server'
complete -c probe-rs -n __fish_use_subcommand -f -a debug -d 'Basic command line debugger'
complete -c probe-rs -n __fish_use_subcommand -f -a download -d 'Download memory to attached target'
complete -c probe-rs -n __fish_use_subcommand -f -a erase -d 'Erase all nonvolatile memory of attached target'
complete -c probe-rs -n __fish_use_subcommand -f -a run -d 'Flash and run an ELF program'
complete -c probe-rs -n __fish_use_subcommand -f -a attach -d 'Attach to rtt logging'
complete -c probe-rs -n __fish_use_subcommand -f -a trace -d 'Trace a memory location on the target'
complete -c probe-rs -n __fish_use_subcommand -f -a itm -d 'Configure and monitor ITM trace packets from the target'
complete -c probe-rs -n __fish_use_subcommand -f -a chip -d 'Inspect internal registry of supported chips'
complete -c probe-rs -n __fish_use_subcommand -f -a benchmark -d 'Measure the throughput of the selected debug probe'
complete -c probe-rs -n __fish_use_subcommand -f -a profile -d 'Profile on-target runtime performance of target ELF program'
complete -c probe-rs -n __fish_use_subcommand -f -a read -d 'Read from target memory address'
complete -c probe-rs -n __fish_use_subcommand -f -a write -d 'Write to target memory address'
complete -c probe-rs -n __fish_use_subcommand -f -a complete -d 'Install and complete autocomplete scripts'
complete -c probe-rs -n __fish_use_subcommand -f -a mi
complete -c probe-rs -n __fish_use_subcommand -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from dap-server" -l port -d 'IP port number to listen for incoming DAP connections, e.g. "50000"' -r
complete -c probe-rs -n "__fish_seen_subcommand_from dap-server" -l ip -d 'IP address to listen for incoming DAP connections, e.g. "127.0.0.1"' -r
complete -c probe-rs -n "__fish_seen_subcommand_from dap-server" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from dap-server" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from dap-server" -l single-session -d 'Some editors and IDEs expect the debug adapter processes to exit at the end of every debug session (on receiving a `Disconnect` or `Terminate` request)'
complete -c probe-rs -n "__fish_seen_subcommand_from dap-server" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from dap-server" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from list" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from list" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from list" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l target-sel -d 'SWD Multidrop target selection value' -r
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from info" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from info" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from info" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l core -r
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from reset" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l gdb-connection-string -d 'Use this flag to override the default GDB connection string (localhost:1337).' -r
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l reset-halt -d 'Use this flag to reset and halt (instead of just a halt) the attached core after attaching to the target.'
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from gdb" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l core -r
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l exe -d 'Binary to debug' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from debug" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l flash-layout -d 'Requests the flash builder to output the layout into the given file in SVG format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l binary-format -d 'If a format is provided, use it. If a target has a preferred format, we use that. Finally, if neither of the above cases are true, we default to ELF' -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l base-address -d 'The address in memory where the binary will be put at. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l skip -d 'The number of bytes to skip at the start of the binary file. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l idf-bootloader -d 'The idf bootloader path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l idf-partition-table -d 'The idf partition table path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from download" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l chip-erase -d 'Whether to erase the entire chip before downloading'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l disable-progressbars
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l disable-double-buffering -d 'Use this flag to disable double-buffering when downloading flash data. If download fails during programming with timeout errors, try this option'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l restore-unwritten -d 'Enable this flag to restore all bytes erased in the sector erase but not overwritten by any page'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l verify -d 'After flashing, read back all the flashed data to verify it has been written correctly'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from download" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from erase" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l format -d 'Configure formatting of the test report output' -r -f -a "{pretty	'One line per test. Output for humans. (default)',terse	'One character per test. Usefull for test suites with many tests',json	'Json output'}"
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l skip-test -d 'Skip tests whose names contain FILTER (this flag can be used multiple times)' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -s Z -d 'No-op, ignored. Flag only exists for CLI compatibility with libtest' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l flash-layout -d 'Requests the flash builder to output the layout into the given file in SVG format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l binary-format -d 'If a format is provided, use it. If a target has a preferred format, we use that. Finally, if neither of the above cases are true, we default to ELF' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l base-address -d 'The address in memory where the binary will be put at. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l skip -d 'The number of bytes to skip at the start of the binary file. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l idf-bootloader -d 'The idf bootloader path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l idf-partition-table -d 'The idf partition table path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l log-format -d 'The default format string to use for decoding defmt logs' -r
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from run" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l catch-reset -d 'Enable reset vector catch if its supported on the target'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l catch-hardfault -d 'Enable hardfault vector catch if its supported on the target'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l list -d 'List all tests instead of executing them'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l exact -d 'If set, filters are matched exactly rather than by substring'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l nocapture
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l show-output -d 'No-op, ignored. libtest-mimic does not currently capture stdout'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l disable-progressbars
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l disable-double-buffering -d 'Use this flag to disable double-buffering when downloading flash data. If download fails during programming with timeout errors, try this option'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l restore-unwritten -d 'Enable this flag to restore all bytes erased in the sector erase but not overwritten by any page'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l verify -d 'After flashing, read back all the flashed data to verify it has been written correctly'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l always-print-stacktrace -d 'Always print the stacktrace on ctrl + c'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l chip-erase -d 'Whether to erase the entire chip before downloading'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l no-location -d 'Suppress filename and line number information from the rtt log'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l rtt-scan-memory -d 'Scan the memory to find the RTT control block'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from run" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l format -d 'Configure formatting of the test report output' -r -f -a "{pretty	'One line per test. Output for humans. (default)',terse	'One character per test. Usefull for test suites with many tests',json	'Json output'}"
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l skip-test -d 'Skip tests whose names contain FILTER (this flag can be used multiple times)' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -s Z -d 'No-op, ignored. Flag only exists for CLI compatibility with libtest' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l flash-layout -d 'Requests the flash builder to output the layout into the given file in SVG format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l binary-format -d 'If a format is provided, use it. If a target has a preferred format, we use that. Finally, if neither of the above cases are true, we default to ELF' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l base-address -d 'The address in memory where the binary will be put at. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l skip -d 'The number of bytes to skip at the start of the binary file. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l idf-bootloader -d 'The idf bootloader path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l idf-partition-table -d 'The idf partition table path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l log-format -d 'The default format string to use for decoding defmt logs' -r
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l catch-reset -d 'Enable reset vector catch if its supported on the target'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l catch-hardfault -d 'Enable hardfault vector catch if its supported on the target'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l list -d 'List all tests instead of executing them'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l exact -d 'If set, filters are matched exactly rather than by substring'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l nocapture
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l show-output -d 'No-op, ignored. libtest-mimic does not currently capture stdout'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l disable-progressbars
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l disable-double-buffering -d 'Use this flag to disable double-buffering when downloading flash data. If download fails during programming with timeout errors, try this option'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l restore-unwritten -d 'Enable this flag to restore all bytes erased in the sector erase but not overwritten by any page'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l verify -d 'After flashing, read back all the flashed data to verify it has been written correctly'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l always-print-stacktrace -d 'Always print the stacktrace on ctrl + c'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l chip-erase -d 'Whether to erase the entire chip before downloading'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l no-location -d 'Suppress filename and line number information from the rtt log'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l rtt-scan-memory -d 'Scan the memory to find the RTT control block'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from attach" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l core -r
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from trace" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l core -r
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -f -a memory -d 'Direct ITM data to Embedded Trace Buffer/FIFO (ETB/ETF) for extraction'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -f -a swo -d 'Direct ITM traffic out the TRACESWO pin for reception by the probe'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from memory" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from memory" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from memory" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from memory" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from swo" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from swo" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from swo" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from swo" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -f -a memory -d 'Direct ITM data to Embedded Trace Buffer/FIFO (ETB/ETF) for extraction'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -f -a swo -d 'Direct ITM traffic out the TRACESWO pin for reception by the probe'
complete -c probe-rs -n "__fish_seen_subcommand_from itm; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -f -a list -d 'Lists all the available families and their chips with their full'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -f -a info -d 'Shows chip properties of a specific chip'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from list" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from list" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from list" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from info" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from info" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from info" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -f -a list -d 'Lists all the available families and their chips with their full'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -f -a info -d 'Shows chip properties of a specific chip'
complete -c probe-rs -n "__fish_seen_subcommand_from chip; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l address -d 'Start address for the benchmark test' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l min-speed -d 'Minimum speed for the debug probe' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l max-speed -d 'Maximum speed for the debug probe' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l word-size -d 'Word size for read/write accesses' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l iterations -d 'Number of times to run each test' -r
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from benchmark" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l format -d 'Configure formatting of the test report output' -r -f -a "{pretty	'One line per test. Output for humans. (default)',terse	'One character per test. Usefull for test suites with many tests',json	'Json output'}"
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l skip-test -d 'Skip tests whose names contain FILTER (this flag can be used multiple times)' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -s Z -d 'No-op, ignored. Flag only exists for CLI compatibility with libtest' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l flash-layout -d 'Requests the flash builder to output the layout into the given file in SVG format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l binary-format -d 'If a format is provided, use it. If a target has a preferred format, we use that. Finally, if neither of the above cases are true, we default to ELF' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l base-address -d 'The address in memory where the binary will be put at. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l skip -d 'The number of bytes to skip at the start of the binary file. This is only considered when `bin` is selected as the format' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l idf-bootloader -d 'The idf bootloader path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l idf-partition-table -d 'The idf partition table path' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l log-format -d 'The default format string to use for decoding defmt logs' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l duration -d 'Duration of profile in seconds' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l core -d 'Which core to profile' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l limit -d 'Limit the number of entries to output' -r
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l catch-reset -d 'Enable reset vector catch if its supported on the target'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l catch-hardfault -d 'Enable hardfault vector catch if its supported on the target'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l list -d 'List all tests instead of executing them'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l exact -d 'If set, filters are matched exactly rather than by substring'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l nocapture
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l show-output -d 'No-op, ignored. libtest-mimic does not currently capture stdout'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l disable-progressbars
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l disable-double-buffering -d 'Use this flag to disable double-buffering when downloading flash data. If download fails during programming with timeout errors, try this option'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l restore-unwritten -d 'Enable this flag to restore all bytes erased in the sector erase but not overwritten by any page'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l verify -d 'After flashing, read back all the flashed data to verify it has been written correctly'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l always-print-stacktrace -d 'Always print the stacktrace on ctrl + c'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l chip-erase -d 'Whether to erase the entire chip before downloading'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l no-location -d 'Suppress filename and line number information from the rtt log'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l rtt-scan-memory -d 'Scan the memory to find the RTT control block'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l flash -d 'Flash the ELF before profiling'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l line-info -d 'Print file and line info for each entry'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -f -a naive -d 'Naive, Halt -> Read PC -> Resume profiler'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -f -a itm -d 'Use the Itm port to profile the chip (ARM only)'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from naive" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from naive" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from naive" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from naive" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from itm" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from itm" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from itm" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from itm" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -f -a naive -d 'Naive, Halt -> Read PC -> Resume profiler'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -f -a itm -d 'Use the Itm port to profile the chip (ARM only)'
complete -c probe-rs -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l core -r
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from read" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from read" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from read" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l core -r
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l chip -r
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l chip-description-path -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l protocol -d 'Protocol used to connect to chip. Possible options: [swd, jtag]' -r
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l probe -d 'Use this flag to select a specific probe in the list' -r
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l speed -d 'The protocol speed in kHz' -r
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from write" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l connect-under-reset -d 'Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip'
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l dry-run
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l allow-erase-all -d 'Use this flag to allow all memory, including security keys and 3rd party firmware, to be erased even when it has read-only protection'
complete -c probe-rs -n "__fish_seen_subcommand_from write" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from write" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -l shell -r -f -a "{bash	'',elvish	'',fish	'',powershell	'',zsh	''}"
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a install -d 'Installs the autocomplete script for the correct shell'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a probe-list -d 'Lists the probes that are currently plugged in in a way that the shell understands'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a chip-list -d 'Lists the chips in a way that the shell understands'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from install" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from install" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from install" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from probe-list" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from probe-list" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from probe-list" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from probe-list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from chip-list" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from chip-list" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from chip-list" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from chip-list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a install -d 'Installs the autocomplete script for the correct shell'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a probe-list -d 'Lists the probes that are currently plugged in in a way that the shell understands'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a chip-list -d 'Lists the chips in a way that the shell understands'
complete -c probe-rs -n "__fish_seen_subcommand_from complete; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -f -a meta
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and __fish_seen_subcommand_from meta" -l log-file -d 'Location for log file' -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and __fish_seen_subcommand_from meta" -s r -l report -r -F
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and __fish_seen_subcommand_from meta" -l log-to-folder -d 'Enable logging to the default folder. This option is ignored if `--log-file` is specified'
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and __fish_seen_subcommand_from meta" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -f -a meta
complete -c probe-rs -n "__fish_seen_subcommand_from mi; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from meta; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a dap-server -d 'Debug Adapter Protocol (DAP) server. See <https://probe.rs/docs/tools/debugger/>'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a list -d 'List all connected debug probes'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a info -d 'Gets info about the selected debug probe and connected target'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a reset -d 'Resets the target attached to the selected debug probe'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a gdb -d 'Run a GDB server'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a debug -d 'Basic command line debugger'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a download -d 'Download memory to attached target'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a erase -d 'Erase all nonvolatile memory of attached target'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a run -d 'Flash and run an ELF program'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a attach -d 'Attach to rtt logging'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a trace -d 'Trace a memory location on the target'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a itm -d 'Configure and monitor ITM trace packets from the target'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a chip -d 'Inspect internal registry of supported chips'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a benchmark -d 'Measure the throughput of the selected debug probe'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a profile -d 'Profile on-target runtime performance of target ELF program'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a read -d 'Read from target memory address'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a write -d 'Write to target memory address'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a complete -d 'Install and complete autocomplete scripts'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a mi
complete -c probe-rs -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dap-server; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from gdb; and not __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from erase; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from attach; and not __fish_seen_subcommand_from trace; and not __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from benchmark; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from read; and not __fish_seen_subcommand_from write; and not __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo" -f -a memory -d 'Direct ITM data to Embedded Trace Buffer/FIFO (ETB/ETF) for extraction'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from itm; and not __fish_seen_subcommand_from memory; and not __fish_seen_subcommand_from swo" -f -a swo -d 'Direct ITM traffic out the TRACESWO pin for reception by the probe'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info" -f -a list -d 'Lists all the available families and their chips with their full'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from chip; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from info" -f -a info -d 'Shows chip properties of a specific chip'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm" -f -a naive -d 'Naive, Halt -> Read PC -> Resume profiler'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from naive; and not __fish_seen_subcommand_from itm" -f -a itm -d 'Use the Itm port to profile the chip (ARM only)'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list" -f -a install -d 'Installs the autocomplete script for the correct shell'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list" -f -a probe-list -d 'Lists the probes that are currently plugged in in a way that the shell understands'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from complete; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from probe-list; and not __fish_seen_subcommand_from chip-list" -f -a chip-list -d 'Lists the chips in a way that the shell understands'
complete -c probe-rs -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from mi; and not __fish_seen_subcommand_from meta" -f -a meta
