# Cargo global configuration file
# Location: ~/.cargo/config.toml
# This file is optional — Cargo uses defaults if it's missing.

# [build]
# jobs = 4
# target-dir = "/home/username/.cargo/target"

# [term]
# verbose = true
# color = "always"

# [env]
# RUSTFLAGS = "-C target-cpu=native"

# [registries]
# my-registry = { index = "https://my-registry.example.com/index" }

# [init]
# name = "Your Name"
# edition = "2021"
# vcs = "git"
