#!/usr/bin/env sh

BEMENU_OPTS="--fb '#1e1e2e' --ff '#cdd6f4' --nb '#1e1e2e' --nf '#cdd6f4' --tb '#1e1e2e' --tf '#f32ba8' --hb '#1e1e2e' --hf '#f9e2af' --ab '#1e1e2e' --af '#cdd6f4' --fn 'Monospace 10' -H 28 --ch 20 --prompt 'run' -i --hp 8" /usr/bin/bemenu-run
